CC = 'cc'
CFLAGS = '-Wall'

desc 'Builds pv.c the Play Video test.'
task :pv do
    sh "#{CC} #{CFLAGS} pv.c -o pv `pkg-config --cflags --libs theoraplay`"
end

desc 'Builds test_audio.c the SDL2 audio(WAV) test.'
task :test_audio do
    sh "#{CC} #{CFLAGS} test_audio.c -o test_audio `pkg-config --cflags --libs sdl2`"
end
